import Head from 'next/head'
import { useEffect, useState } from 'react';
import CnavBar from '../Components/CnavBar';
import HomePage from '../Components/HomePage';
import Authenticate from '../Components/Authenticate';
import jwt from 'jsonwebtoken';
import { useDispatch, useSelector } from 'react-redux';
import { setAllBlogs } from '../state/stateSlice';


export default function Home({ creating, setCreating}) {
  const [user, setUser] = useState(null)
  const [datas, setDatas] = useState(null)
  const dispatch = useDispatch()
  const apiUrl = useSelector(state => state.all.apiUrl)

  useEffect(async () => {
    const token = localStorage.getItem('token')
    console.log(token)
    const res = await fetch(`${apiUrl}/blogs`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      'Authorization':  token
    },}

  );
  const data = await res.json();
  dispatch(setAllBlogs(data))
  setDatas(data)
  // console.log()
  if(token){
    setUser(jwt.decode(token))
    console.log(user)
    }
  }, [])
 
  return (
    <div>
      <Head>
        <title>Topics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* JUST SIMPLE PROPS DRILLING, NOTHING TO SEE HERE */}
        {
          user ?
          <HomePage datas={datas}/>
          :
          <Authenticate/>

        }
      </main>
    </div>
  )
}


// ! content is dynamic so ssr is not necessary | required
// export const getStaticProps = async () => {
//   const res = await fetch('http://localhost:5000/blogs', {
//     method: 'GET',
//     headers: {
//       'Content-Type': 'application/json',
//       'Authorization': localStorage.getItem('token')
//     },}

//   );
//   const data = await res.json();
//   // console.log(data)

//   if (!data) {
//     return {
//       notFound: true,
//     }
//   }
//   return {
//     props: {
//       datas: data,
//     },
//   };
// }  
